### ISSUE TITLE
Config: underscores in numeric literals

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#136]
Doesn't look like Bootique can parse numeric literals in configs that are using Java 8 style with underscores. E.g.:

```
scheduler:
  threadPoolSize: 2
  triggers:
    - fixedDelayMs: 1_800_000
      initialDelayMs: 10_000
```
causes
`com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value '1_800_000': not a valid Long value`

An alternative solution may be to map each number using a specialized value object... LIke the above is a time interval that can be expressed in second or minutes
