### ISSUE TITLE
BQ_* vars case insensitivity

### ISSUE THREAD

**Issue by ebondareva** [bootique/bootique#177]
It's necessatry to make BQ_* vars case sensitive to prevent ambiguous configs. Let's consider vars contributed into BQ via extender:
```
BQ_JDBC_MYDB_URL, my:url
BQ_jdbc_MYDB_Url, jdbc:camel
...
```
Both vars bound to the same path but declared in different cases (upper and camel). Both will be applied to the YAML in random order, so that config would be:
```yaml
jdbc:
  mydb:
    url: jdbc:camel
```
Alternatively:
```yaml
jdbc:
  mydb:
    url: my:url
```
