### ISSUE TITLE
Duration value object

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#219]
Similar for #218, only a value object to express durations. This will provide a human-readable alternative for ISO8601 `java.time.Duration`. This will enrich custom configurations and app models, including[ health check thresholds](https://github.com/bootique/bootique-metrics/issues/27), etc.

```yml
threeMilliseconds: 3ms
threeMilliseconds: "3 ms"
fourSeconds: 4s
fourSeconds: 4sec
secondsWithFractions: 15.003s
fiveAndHalfMinutes: "5.5min"
oneHour: 1hr
oneHour: 1hour
oneDay: 1day
```

Also must be `Comparable`, implement `equals` and `hashCode`.
