### ISSUE TITLE
Help wanted for getting scalar configuration variable values for replacing placeholders

### ISSUE THREAD

**Issue by gpaulissen** [bootique/bootique#294]
I use the bootique flyway module to execute database migrations for 4 schemas (and 4 different locations) after each other and I want to minimise the number of scripts.

My idea:

1. Invoke the bootique job module with a YAML to execute 4 Flyway jobs in order AND with a YAML defining the placeholders variables
2. Each job has several parameters: database schema, Flyway YAML config file and Flyway command (info, migrate, etcetera).
3. I create a temporary config file using Apache commons string substitution.
4. The job invokes the Bootique.app with a new command line including the temporary config file and the Flyway command.

So I have a Flyway YAML configuration file that starts like:

`jdbc:
  oracle:
    url: jdbc:oracle:thin:@//${db.host}:${db.port}/${db.service}
    driverClassName: oracle.jdbc.OracleDriver
    username: ${db.username}
    password: ${db.password}
`

The variables are in another YAML file:

`db:
  host: 127.0.0.1
  port: 1526
  service: ORCL
  username: SCOTT
  password: TIGER
`

I am having problems with step 3. I have no idea how to get the values for each "db." variable. And I prefer not to use Java system properties, at least not on the first command line invocation.

**Comment by andrus** [comment]
Hi! Yeah, variables substitution was kept out of config files by design. We do merge YAML/JSON configs by key. So making *values* dynamic doesn't buy us very little, but adds a level of indirection and complexity. E.g. compare these two configs:

```yaml
# standard Bootique
jdbc: 
  oracle: 
    url: jdbc:oracle:thin:@//host1:1234/db1
    username: user1
    password: password1
```
```yaml
# your custom alternative
db: 
  host: 127.0.0.1 
  port: 1526 
  service: ORCL 
  username: SCOTT 
  password: TIGER 
```
Bootique one isn't even more verbose. So one possible standard approach would be to create one shared config files:
```yaml
jdbc: 
  oracle: 
    driverClassName: oracle.jdbc.OracleDriver 
```
and any number of db-specific files like the one mentioned on top. And then start the app with two `--config` options:

```
java -jar myapp.jar --config standard.yaml --config db1.yaml
```
Bootique will do the merging of `standard.yaml` and `db1.yaml` and off you go.

> I prefer not to use Java system properties
I am with you on that.

**Comment by andrus** [comment]
Incidentally been reading [HikariCP configuration docs](https://github.com/brettwooldridge/HikariCP#essentials), and they mention "url-free" configuration approach (as the preferred approach no less), based on "dataSourceClassName" property. This allows to pass host name, port, etc. as individual properties:

```yaml
jdbc:
  db:
    dataSourceClassName: oracle.jdbc.pool.OracleDataSource
    dataSourceProperties:
          # These are javaBean properties of OracleDataSource
	  serverName: 127.0.0.1 
	  portNumber: 1526 
	  serviceName: ORCL 
	  user: SCOTT 
	  password: TIGER 
```

Don't know if this makes thing better or worse :)
